[flags]
hide_avg_cpu = true
dot_marker = false
left_legend = false
current_usage = false
group_processes = false
case_sensitive = false
whole_word = false
regex = false
basic = false
use_old_network_legend = false
battery = false
rate = 250
default_time_value = 120000
time_delta = 1000
hide_time = true
temperature_type = "celsius"
default_widget_type = "proc"
# default_widget_count = 4 # ?? i dont understand
disable_click = true
color = "nord"
enable_cache_memory = true
mem_as_value = true
tree = false
# show_table_scroll_position = false # ?? i dont understand
process_command = false
disable_advanced_kill = false
network_use_binary_prefix = true
network_use_bytes = false
network_use_log = false
enable_gpu = true
# retention = "120s" # ?? i dont understand
unnormalized_cpu = false 
expanded_on_startup = false

[processes]
columns = ["pid", "name", "cpu%", "mem%", "read", "write", "state"]

[[row]]
  ratio = 3
  [[row.child]]
    ratio = 8
    type = "cpu"
  [[row.child]]
    ratio = 2
    type = "temp"
[[row]]
  ratio = 7
  [[row.child]]
    ratio = 4
    [[row.child.child]]
      ratio = 6
      type = "mem"
    [[row.child.child]]
      ratio = 4
      type = "net"
  [[row.child]]
  	ratio = 6
    type = "proc"
